config/routes.rb
Rails.application.routes.draw do
  resources :books
  resource :sign_in, only: [:new, :show, :create]
  resource :sign_up, only: [:show, :create]
  resource :welcome, only: [:show]
  resource :sign_out, only: [:destroy]

   root 'welcomes#show'

end

app/models/book.rb
require 'file_size_validator'
class Book < ActiveRecord::Base
  validates :page_count, :presence => true
  validates :genre, :presence => true
  validates :title, :presence => true
  scope :descending, -> { order 'created_at DESC' }
  # Tells rails to use this uploader for this model.
  mount_uploader :attachment, AttachmentUploader 
    validates :attachment, 
      :presence => true, 
      :file_size => { 
      :maximum => 1.megabyte
      } 

  def self.search(search)
      where('title LIKE ? OR genre LIKE ?',"%#{search}%", "%#{search}%") 
       # where('genre LIKE ?', "%#{search}%").all
  end
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
  validates :username, presence: true
  validates :password, confirmation: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def authenticate
    if current_user.nil?
      redirect_to welcome_path, notice: "Please log in to see the library's contents"
    end
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # def logged_and_logged_out
  #    # debugger
  #   'logged_out' if @current_user.nil?
  # end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_filter :authenticate
  def index
    if params[:search].present?
      @books = Book.search(params[:search]).page(params[:page]).per(2)
    else
      @books = Book.descending.page(params[:page]).per(6)
    end
  end

  def new
    @book = Book.new
  end

  def show
     @book = Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_path
    else
      render action: :new
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    if @book.destroyed?
      redirect_to action: :index
    else
      render @book.errors
    end
  end

   private

  def book_params
    params.require(:book).permit(:genre, :attachment, :title, :page_count)
  end
end

app/controllers/sign_ins_controller.rb
class SignInsController < ApplicationController
  def show
    @user = User.new
  end
  
  def create
    @user = User.find_by(username: user_params[:username])
     if @user.authenticate(user_params[:password])
      redirect_to books_path(@user)
      session[:user_id] = @user.id
    else
      redirect_to books_path
    end  
  end 

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/sign_outs_controller.rb
class SignOutsController < ApplicationController
  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end
end

app/controllers/sign_ups_controller.rb
class SignUpsController < ApplicationController
  def show
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    # debugger
    if @user.save
       session[:user_id] = @user.id
      redirect_to books_path, notice: "Sign up successful"
    else
      redirect_to sign_up_path, notice: @user.errors
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  # layout :logged_and_logged_out  
  def show
    render layout: 'welcome'
  end
end

app/views/books/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Maria's Library</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
   
        <li class="active">
          <a href="#">Books
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li>
          <a href="/books/new">
            Add a Book
          </a>
        </li>
      </ul>
      
      
      <ul class="nav navbar-nav navbar-right">
      <% if @current_user %>
        <li>
        <%= link_to("Logout #{@current_user.username }", sign_out_path, :method => :delete) %> 
<!--           <a href="/sign_out_path"> logout <%= @current_user.username %></a> -->
        </li>
      <% end %>
      
       
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/books/index.html.erb
<%= render partial: "navbar", object: @current_user %>
<div class="well">
  <h1>Books</h1>
  <%= paginate @books %>
  <div>
    <%= form_tag books_path, :method => 'get' do %>
      <div class="row">
        <div class="form-group col-md-10 col-lg-4">
          <%= text_field_tag :search, params[:search], :class=>"form-control",  :placeholder=>"search" %>
        </div>
        <%= submit_tag "Search", :class=>"btn btn-info col-md-1" %>
      </div>
    <% end %>
  </div>
  <div class="image-container">
  <% @books.each do |book|%>
    <div class="col-xs-6 col-md-4">
      <div class="thumbnail">
        <div class="image">
          <%= link_to(image_tag(book.attachment.url), book_path(book)) %> 
        </div>
        <div class="caption">
          <h3>
            <%= content_tag(:p, book.title)%>
          </h3>
          <%= content_tag(:p, "#{book.created_at.strftime("%d %b. %Y")}")%>
        </div>
      </div>
    </div>
  <% end %>
  </div>
<!--     <div class="col-sm-2">
      <input type="search" class="form-control"  placeholder="search">
    </div> -->
</div>

app/views/books/new.html.erb
<h2 class="form-signin-heading">Add a new book</h2> 
<div class="form-horizontal col-md-4">
   <%= form_for @book,  html: { multipart: true } do |f| %>
      <% if @book.errors.present? %>
         <ul>
            <% @book.errors.full_messages.each do |error_message| %>
               <li><%= error_message %></li>
            <% end %>
         </ul>
      <% end %>

      <%= f.label :title %>
     <div class="form-control"> <%= f.text_field :title %> </div>
      <%= f.label :book_count %>
      <%= f.label :attachment %> 
      <div class="form-control"><%= f.file_field :attachment %> </div>
      <%= f.label :genre %>
      
     <div class="form-control"> <%= f.select :genre, ['horror', 'comedy', 'fantasy', 'biography'] %></div>
      <%= f.label :book_count %>
<div class="form-control"> <%= f.text_field :page_count %>
     
      </div>
      <div class="form-control"> <%= f.submit "Save", class: "btn btn-primary" %></div>
     
   <% end %>
   </div>
    

app/views/books/show.html.erb
 <%= render partial: "navbar", object: @current_user %>
 <div class="center-block col-md-3 thumbnail">
   <div id="image-box">
    <div id="image-view">
      <%= image_tag(@book.attachment.url) %> 
    </div>
  </div>
  <div class="caption">
    <h3>
      <%= content_tag(:p, "Title: #{@book.title}")%>
    </h3>
    <h4>
      <%= content_tag(:p, "Genre: #{@book.genre}")%>
    </h4>
    <%= content_tag(:p, "This book was uploaded on #{@book.created_at.strftime("%d %b. %Y")}")%>

    <div id="delete">
      <%= link_to 'Delete book', @book, method: :destroy, data: {confirm: 'Are you sure you want to delete this book?'}%> 
    </div>
  </div>
 </div>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Library</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/logged_out.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns = "http://www.w3.org/1999/xhtml">

   <head>
      <meta http-equiv = "Content-Type" content = "text/html; charset = iso-8859-1" />
      <meta http-equiv = "Content-Language" content = "en-us" />
      <title>Library Info System</title>
      <%= stylesheet_link_tag "style" %>
   </head>

   <body id = "library">
      <div id = "container">
         
         <div id = "header">
<!--       <p><%= button_to "Sign out", sign_in_path, :method => :delete %> </p>  -->
            <h1 id="title">This is Maria's library</h1>
             <h3>Please <%=
              link_to "log in",sign_in_path
               %> to continue </h3> 
         </div>

         <div id ="content">
            <%= yield %>
         </div>

         <div id = "sidebar"></div>
         
      </div>
   </body>
   
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset = iso-8859-1" />
    <meta http-equiv="Content-Language" content="en-us" />
    <title>Library Info System</title>
    <%= stylesheet_link_tag "application", "style" %>
  </head>

  <body id="library">
    <div id="welcome-container">
      <div id="container">
         <div id="header">
            <h1>This is Maria's library</h1>
            <!-- TODO remove cross-over line over link -->
            <h2>Please <%= link_to "log in",sign_in_path %> to continue </h2> 
         </div>

         <div id="content">
            <%= yield %>
         </div>

         <div id="sidebar"></div>
      </div>
    </div>
   </body>
</html>

app/views/sign_ins/show.html.erb
  <% if flash[:notice] %>
    <%= flash[:notice]%>
  <% end %> 

  <%= form_for(@user, url: sign_in_path) do |f| %>
    <div class="container">
      <h2 class="form-signin-heading">Please sign in</h2> 
      <div class="row">
        <div class="form-group col-md-4">
          <%= f.label :username %>
          <%= f.text_field :username, :class=>"form-control" %> 
        </div>
      </div>

      <div class="row">
        <div class="form-group col-md-4">
          <%= f.label :password %>
          <%= f.password_field :password, :class=>"form-control" %>
        </div>
      </div>
      <%= f.submit "Sign In", :class=>"btn btn-primary" %>
      <%= link_to "Sign up", sign_up_path, :class=>"btn btn-default" %>
    </div>
  <% end %>

app/views/sign_ups/show.html.erb
<% if flash[:notice] %>
<p> <%= flash[:notice]%></p>
<% end %>
<h2 class="form-signin-heading">Sign up</h2> 
<div class="form-group">
  <%= form_for(@user, role: "form", url: sign_up_path) do |f| %>

   <div class="control-label"> <%= f.label :username %></div>
   <div class="form-control"><%= f.text_field :username %> 

   <div class="control-label"> <%= f.label :password %></div>
    <div class="form-control"<%= f.password_field :password %></div>  

    <div class="form-control"> <%= f.submit "Submit" %> </div> 
  <% end %>
 </div>